version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 160594
    ports:
      - "5432:5432"
  discord:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
